name: Build Pack

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create texture pack ZIP
        run: |
          # Create the ZIP file and exclude unnecessary files
          zip -r pack.zip . -x ".git/*" ".github/*" "*.yml" "README.md"

      - name: Move only pack.zip to a folder for deployment
        run: |
          # Create 'public' folder and move only the 'pack.zip' file to it
          mkdir -p public
          mv pack.zip public/